"""
Schema self-consistency checks for every data plugin's ``get_empty_settings()``.

``tests/unit/plugins/test_plugin_compliance.py`` checks that a plugin *declares*
the right interface. This module checks that the settings schema a plugin hands
out actually describes itself correctly: that every parameter carries the keys
:py:meth:`~poriscope.utils.BaseDataPlugin.BaseDataPlugin.get_empty_settings`
documents as required, and that any default value the plugin ships would survive
that same plugin's own validators.

The contract being enforced is the one in that method's docstring, which is
autogenerated into the plugin-development docs:

    Min, Max, and Options can be skipped or explicitly set to None if they are
    not used. Value and Type are required. All values provided must be
    consistent with Type.

``BaseDataPlugin.Setting`` agrees - it declares both ``Type`` and ``Value``
non-optional.

Why this is not already covered:

- ``test_plugin_compliance.py`` never calls the plugin.
- The per-plugin unit tests build instances via ``object.__new__`` and inject
  settings directly, so they never see ``get_empty_settings()``'s own output.
- ``tests/integration/flows/`` and ``tests/e2e/`` hand-write correct values over
  the defaults (``fset["Cutoff"]["Value"] = 200_000.0``), so a wrong default is
  overwritten before it reaches a validator.
- In the GUI, ``DictDialog.on_ok`` coerces every value through
  ``self.params[key]["Type"](...)``, which masks a mismatched default entirely.

That last point is why these checks matter despite the app working: the defaults
are only reachable un-coerced by a programmatic caller - a script, a headless
flow, or the settings-filling layer a behavioural conformance suite needs.

The static (schema-only) half of what this module checks lives in
:py:mod:`poriscope.utils.settings_schema` as ``validate_settings_schema()``, so it
is reusable outside pytest - see ``scripts/check_settings_schema.py``, which the
``settings-schema`` pre-commit hook runs on every ``poriscope/plugins/**`` change.
"""

import importlib
import inspect
import pkgutil
from typing import Any, Dict, List, Set, Type

import pytest

import poriscope.plugins as plugins_pkg
from poriscope.utils.BaseDataPlugin import BaseDataPlugin
from poriscope.utils.settings_schema import FILE_PARAM_KEYS, validate_settings_schema

# Import everything under poriscope.plugins so that __subclasses__() below sees
# every plugin. Same approach, and same reason, as test_plugin_compliance.py.
for _finder, _modname, _ispkg in pkgutil.walk_packages(
    plugins_pkg.__path__, prefix=f"{plugins_pkg.__name__}."
):
    importlib.import_module(_modname)


# Parameters whose value is a live plugin instance rather than a scalar. They are
# keyed by the name of the Meta* family they accept, and BaseDataPlugin's direct
# subclasses are exactly that set of families, so deriving it here keeps this in
# step with any new family without a list to maintain.
#
# These are excluded from the default-value checks: such a parameter's declared
# Type is str (it describes the pre-resolution dropdown key, not the resolved
# value), while the family validators - e.g. MetaEventFinder._validate_param_types
# - require an object inheriting the Meta* base. No standalone schema can satisfy
# both, so there is nothing self-consistent to assert.
PLUGIN_DEPENDENCY_KEYS: Set[str] = {
    cls.__name__ for cls in BaseDataPlugin.__subclasses__()
}


def get_concrete_data_plugins() -> List[Type[BaseDataPlugin]]:
    """
    Collect every instantiable data plugin discovered under ``poriscope.plugins``.

    :return: Concrete (non-abstract) subclasses of BaseDataPlugin, ordered by name.
    :rtype: List[Type[BaseDataPlugin]]
    """
    found: Set[Type[BaseDataPlugin]] = set()
    queue: List[Type[BaseDataPlugin]] = list(BaseDataPlugin.__subclasses__())
    while queue:
        cls = queue.pop()
        if cls in found:
            continue
        found.add(cls)
        queue.extend(cls.__subclasses__())
    return sorted(
        (cls for cls in found if not inspect.isabstract(cls)),
        key=lambda cls: cls.__name__,
    )


CONCRETE_PLUGINS: List[Type[BaseDataPlugin]] = get_concrete_data_plugins()

plugin_cases = pytest.mark.parametrize(
    "plugin_cls",
    CONCRETE_PLUGINS,
    ids=[cls.__name__ for cls in CONCRETE_PLUGINS],
)


def get_empty_settings_for(plugin_cls: Type[BaseDataPlugin]) -> Dict[str, Any]:
    """
    Instantiate a plugin unconfigured and return the settings schema it offers.

    ``standalone=True`` is the form every non-GUI caller uses, and the only form
    that does not require a populated globally_available_plugins mapping.

    :param plugin_cls: The plugin class under test.
    :type plugin_cls: Type[BaseDataPlugin]
    :return: The schema returned by the plugin's get_empty_settings().
    :rtype: Dict[str, Any]
    """
    return plugin_cls().get_empty_settings(standalone=True)


@pytest.mark.compliance
@plugin_cases
def test_settings_schema_shape(plugin_cls: Type[BaseDataPlugin]) -> None:
    """
    Every parameter declares the keys the contract requires, and no others.

    Delegates to :py:func:`poriscope.utils.settings_schema.validate_settings_schema`
    - see its docstring for exactly what is checked. Keeping the check itself in
    ``poriscope/utils/`` rather than here is what lets
    ``scripts/check_settings_schema.py`` (and the pre-commit hook that runs it)
    reuse it without needing pytest.

    :param plugin_cls: The plugin class under test.
    :type plugin_cls: Type[BaseDataPlugin]
    """
    settings = get_empty_settings_for(plugin_cls)
    errors = validate_settings_schema(settings)
    assert not errors, f"{plugin_cls.__name__} settings schema:\n  " + "\n  ".join(
        errors
    )


@pytest.mark.compliance
@plugin_cases
def test_settings_defaults_pass_own_validators(
    plugin_cls: Type[BaseDataPlugin],
) -> None:
    """
    Any default a plugin ships must satisfy that plugin's own validators.

    Only parameters carrying a usable default are checked. Three encodings mean
    "the caller must supply this", and all three are skipped here: the ``Value``
    key omitted, ``Value`` explicitly None, and - for plugin-dependency
    parameters - ``Value`` as an empty string.

    The real validators are invoked rather than reimplemented, so this stays
    correct if the rules in ``_validate_param_types`` /
    ``_validate_param_ranges`` change.

    :param plugin_cls: The plugin class under test.
    :type plugin_cls: Type[BaseDataPlugin]
    """
    plugin = plugin_cls()
    settings = get_empty_settings_for(plugin_cls)

    defaults = {
        param: entry
        for param, entry in settings.items()
        if isinstance(entry, dict)
        and param not in PLUGIN_DEPENDENCY_KEYS
        and entry.get("Value") is not None
    }
    if not defaults:
        pytest.skip(f"{plugin_cls.__name__} ships no default values to check")

    errors: List[str] = []

    try:
        plugin._validate_param_types(defaults)
    except TypeError as exc:
        offenders = [
            f"{param!r}: Type={entry['Type'].__name__} "
            f"but default Value={entry['Value']!r} "
            f"({type(entry['Value']).__name__})"
            for param, entry in defaults.items()
            if isinstance(entry.get("Type"), type)
            and entry["Type"] in (int, float, bool, str)
            and not isinstance(entry["Value"], entry["Type"])
        ]
        errors.append(f"_validate_param_types rejected its own defaults: {exc}")
        errors.extend(offenders)

    try:
        plugin._validate_param_ranges(defaults)
    except ValueError as exc:
        errors.append(f"_validate_param_ranges rejected its own defaults: {exc}")

    for param, entry in defaults.items():
        options = entry.get("Options")
        if (
            options is not None
            and param not in FILE_PARAM_KEYS
            and entry["Value"] not in options
        ):
            errors.append(
                f"{param!r}: default Value={entry['Value']!r} "
                f"is not among Options={options!r}"
            )

    assert not errors, f"{plugin_cls.__name__} defaults:\n  " + "\n  ".join(errors)
