# MIT License
#
# Copyright (c) 2025 TCossaLab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Contributors:
# Kyle Briggs

import logging
from typing import List, Optional, Tuple

import pandas as pd
from typing_extensions import override

from poriscope.plugins.db_loaders.SQLiteDBLoader import SQLiteDBLoader
from poriscope.utils.DocstringDecorator import inherit_docstrings
from poriscope.utils.LogDecorator import log


@inherit_docstrings
class SQLitePeakDBLoader(SQLiteDBLoader):
    """
    Subclass of MetaDatabaseLoader for reading and querying SQLite database files.

    Provides functionality to load metadata, event data, and other relevant
    structures from a structured SQLite database generated by Poriscope.
    """

    logger = logging.getLogger(__name__)

    @log(logger=logger)
    @override
    def get_plot_features(self, experiment: int, channel: int, index: int) -> Tuple[
        Optional[List[float]],
        Optional[List[float]],
        Optional[List[Tuple[float, float]]],
        Optional[List[str]],
        Optional[List[str]],
        Optional[List[str]],
    ]:
        """
        Get a list of horizontal and vertical lines and associated labels to overlay on the graph generated by construct_fitted_event()

        :param experiment: get only events from this experiment
        :type experiment: int
        :param channel: analyze only events from this channel
        :type channel: int
        :param index: the index of the target event
        :type index: int

        :return: a list of x locations to plot vertical lines and a list of y locations to plot horizontal lines, list of tuples to plot little x's, labels for the vertical lines, labels for the horizontal lines, labels for x's. Must be lists of equal length, or None
        :rtype: Tuple[Optional[List[float]], Optional[List[float]], Optional[List[Tuple[float, float]]], Optional[List[str]], Optional[List[str]], Optional[List[str]]]

        :raises RuntimeError: if fitting is not complete yet
        """

        query = f"""SELECT s.id, s.experiment_id, s.channel_id, s.event_id, e.baseline, e.unfolded_level, e.baseline_std, s.right_ips, s.peak_id, s.left_base, s.right_base, s.peak_loc, s.peak_height, s.right_ips, s.filtered                        FROM sublevels s
                        JOIN events e
                        ON e.id = s.event_db_id
                        WHERE s.experiment_id={experiment} AND s.channel_id={channel} AND s.event_id={index}"""

        valid, debug = self.validate_filter_query(query)
        if valid:
            result = self.query_database_directly(query)
            if len(result) == 0:
                self.logger.info(
                    "Empty dataframe, no features to plot for event",
                    self.__class__.__name__,
                )
                return None, None, None, None, None, None
        else:
            self.logger.debug(
                f"Invalid query syntax in get_plot_features: {self._format_debug_msg(debug)}",
                self.__class__.__name__,
            )
            return None, None, None, None, None, None

        bases = []
        peaks = []
        vlabel = []
        hlabel = []
        plabel = []
        peaks_filtered = []

        # --- 1. Handle Event-Level Data ---
        # Grab the first row for event-level metrics (since they are identical across all rows for this event)
        first_row = result.iloc[0]
        baseline = first_row["baseline"]
        unfolded = first_row["unfolded_level"]
        std = first_row["baseline_std"]

        bases.append(baseline)
        hlabel.append("Baseline")

        bases.append(unfolded + baseline)
        hlabel.append("unfolded level")

        bases.append(unfolded + baseline + std)
        hlabel.append("unfolded level + std")

        bases.append(unfolded + baseline - 2 * std)
        hlabel.append("unfolded level - 2std")

        # --- 2. Handle Sublevel Data ---
        # Iterate over all rows using itertuples for speed
        j = 1
        for row in result.itertuples():
            # Check if peak_id is valid (pd.notna safely handles None/NaN in pandas)
            if pd.notna(row.peak_id):

                # No need for [i] indexing anymore, `row` represents the specific sublevel
                bases.append(row.left_base + row.baseline)
                bases.append(row.right_base + row.baseline)

                hlabel.append(f"Right base #{j}")
                hlabel.append(f"Left base #{j}")

                peaks.append((row.peak_loc, row.peak_height + row.baseline))
                plabel.append(f"Peak #{j}")

                # Filter logic
                if row.filtered not in (0, -1):
                    peaks_filtered.append(row.peak_loc)
                    vlabel.append(f"Type {row.filtered} Peak {j}")

                j += 1
        return peaks_filtered, bases, peaks, vlabel, hlabel, plabel
