# MIT License
#
# Copyright (c) 2025 TCossaLab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Contributors:
# Kyle Briggs

import logging
from typing import List, Optional, Tuple

from typing_extensions import override

from poriscope.plugins.db_loaders.SQLiteDBLoader import SQLiteDBLoader
from poriscope.utils.DocstringDecorator import inherit_docstrings
from poriscope.utils.LogDecorator import log


@inherit_docstrings
class SQLitePeakDBLoader(SQLiteDBLoader):
    """
    Subclass of MetaDatabaseLoader for reading and querying SQLite database files.

    Provides functionality to load metadata, event data, and other relevant
    structures from a structured SQLite database generated by Poriscope.
    """

    logger = logging.getLogger(__name__)

    @log(logger=logger)
    @override
    def get_plot_features(self, experiment: int, channel: int, index: int) -> Tuple[
        Optional[List[float]],
        Optional[List[float]],
        Optional[List[Tuple[float, float]]],
        Optional[List[str]],
        Optional[List[str]],
        Optional[List[str]],
    ]:
        """
        Get a list of horizontal and vertical lines and associated labels to overlay on the graph generated by construct_fitted_event()

        :param experiment: get only events from this experiment
        :type experiment: int
        :param channel: analyze only events from this channel
        :type channel: int
        :param index: the index of the target event
        :type index: int

        :return: a list of x locations to plot vertical lines and a list of y locations to plot horizontal lines, list of tuples to plot little x's, labels for the vertical lines, labels for the horizontal lines, labels for x's. Must be lists of equal length, or None
        :rtype: Tuple[Optional[List[float]], Optional[List[float]], Optional[List[Tuple[float, float]]], Optional[List[str]], Optional[List[str]], Optional[List[str]]]

        :raises RuntimeError: if fitting is not complete yet
        """
        print(experiment, channel, index)

        query = f"""SELECT s.id, s.experiment_id, s.channel_id, s.event_id, e.baseline_current, s.sublevel_blockage
                        FROM sublevels s
                        JOIN events e
                        ON e.id = s.event_db_id
                        WHERE s.experiment_id={experiment} AND s.channel_id={channel} AND s.event_id={index}"""
        print(query)
        ##, e.baseline, e.unfolded_level, e.baseline_std, s.right_ips, s.peak_id, s.left_base, s.right_base, s.peak_loc, s.peak_height, s.right_ips, s.filtered
        valid, debug = self.validate_filter_query(query)
        if valid:
            result = self.query_database_directly(query)
            print(result)
        else:
            raise ValueError(
                f"Invalid query syntax in get_plot_features: {self._format_debug_msg(debug)}"
            )
            self.logger.error(
                f"Invalid query syntax in get_plot_features: {self._format_debug_msg(debug)}",
                self.__class__.__name__,
            )

        return [400], [2000], [(400, 2000)], ["h"], ["v"], ["p"]
