# Build Sphinx and deploy the generated static site to GitHub Pages (branch mode → gh-pages/docs)

name: Build and Deploy Docs to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]
  # Allows manual runs from the Actions tab
  workflow_dispatch:

# Permissions needed to push to the gh-pages branch
permissions:
  contents: write   # peaceiris needs write to push commits to gh-pages

# Allow only one deployment per branch at a time; newest cancels older on same branch
concurrency:
  group: "docs-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  # Single job: build then deploy
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo
      - name: Checkout
        # Keep fetch-depth: 1 (default) — full history not needed
        uses: actions/checkout@v4

      # 2) Build the Sphinx site (docs/source -> docs/build)
      - name: Set up Python 3.12.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx furo

      - name: Build Sphinx HTML
        run: sphinx-build -b html docs/source docs/build

      # Optional sanity checks
      - name: Verify root index.html exists
        run: test -f docs/build/index.html || (echo "Sphinx did not produce docs/build/index.html" && exit 1)

      - name: List docs/build (debug)
        run: ls -la docs/build | sed -n '1,200p'

      # 3) Deploy to GitHub Pages (branch mode)
      #    Your repo Settings → Pages should be:
      #    Source: Deploy from a branch • Branch: gh-pages • Folder: /docs
      - name: Deploy to GitHub Pages (gh-pages/docs)
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # auto-provided token
          publish_dir: docs/build                    # upload this folder's contents
          publish_branch: gh-pages                   # Pages branch
          destination_dir: docs                      # <- land the site under /docs on gh-pages
          enable_jekyll: false                       # create .nojekyll so _static/_sources work
          force_orphan: true                         # clean deploy (single-commit history)

      # 4) (Optional/testing) Also upload the built site as a normal CI artifact
      #    This shows up under the workflow run's "Artifacts" for easy download.
      - name: Upload HTML docs (testing download artifact)
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-html-docs
          path: docs/build
          if-no-files-found: error
          retention-days: 7
