# CI (Branches)
# -----------------------------------------------------------------------------
# What it  does
# - Runs on branch pushes to: develop, feature/*, bugfix/*
# - Installs Linux GUI prereqs for PySide6 (EGL/GL/XCB) + Xvfb virtual display
# - Sets up Python, caches pip by requirements files
# - Installs runtime + dev deps (ruff, black, pytest, pytest-qt, PySide6, etc.)
# - Auto-formats code (ruff --fix, black) and commits fixes back to the branch
# - Runs tests marked "not e2e and not slow" under Xvfb
#
# Why we need the GUI prereqs
# - PySide6/Qt requires native shared libs (libEGL, libGL, XCB) to import QtGui.
# - Xvfb provides a virtual X server so Qt can initialize in headless CI.
#
# Notes / Maintenance
# - Auto-commit requires: permissions.contents=write and checkout fetch-depth: 0
# - Prefer check-only? Replace the lint step with:
#     ruff check .
#     black --check .
#   and remove the commit step; set permissions.contents: read
# - Keep pytest.ini with: qt_api = pyside6
# - Concurrency cancels in-progress runs on the same ref to save compute
# -----------------------------------------------------------------------------

name: CI (Branches)

on:
  # Run this workflow on branch pushes to these patterns
  push:
    branches:
      - develop
      - 'feature/*'
      - 'bugfix/*'

# Needed only because we auto-commit style fixes below.
# If switched to check-only linting, can be set to: { contents: read }
permissions:
  contents: write  # needed for auto-commit on push

# Ensure only one run per branch ref is active; cancel older in-progress runs
concurrency:
  group: ci-branches-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick:
    runs-on: ubuntu-latest

    # Headless Qt rendering; kept even though Xvfb run acts as an extra guard
    env:
      QT_QPA_PLATFORM: offscreen  # run Qt without a display

    steps:
      # Fetch history to enable push changes back (auto-fix commit step)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required to git push later

      # Native libs required for PySide6/Qt on Ubuntu + a virtual display server for GUI tests
      - name: Install system libs for Qt + Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \                     
            libgl1 \                      
            libxkbcommon-x11-0 \          
            libxcb-icccm4 \               
            libxcb-image0 \               
            libxcb-keysyms1 \             
            libxcb-randr0 \               
            libxcb-render-util0 \         
            libxcb-shape0 \               
            libxcb-xfixes0 \              
            xvfb                          

      # Set up Python and enable pip cache keyed by requirements files
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      # Install runtime + dev dependencies (ruff, black, pytest, pytest-qt, PySide6, etc.)
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # Auto-fix style on push (Ruff fixes + Black formatting)
      # If you prefer "check-only", replace with:
      #   ruff check .
      #   black --check .
      # and remove the commit step below.
      - name: Ruff + Black (auto-fix)
        run: |
          ruff check . --fix
          black .

      # Commit and push any formatting changes introduced by the step above
      - name: Commit style fixes if any
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "style: auto-fix (ruff --fix, black)"
            git push
          fi

      # Run unit tests that exclude slow and e2e marks, under a virtual display
      # If no Xvfb, Qt may fail to initialize on headless runners
      - name: Run tests (no slow/e2e) under Xvfb
        run: |
          xvfb-run -a pytest -q -m "not e2e and not slow"
