name: CI (Branches)

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'bugfix/*'

permissions:
  contents: read

concurrency:
  group: ci-branches-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (checks only)
        run: |
          ruff check .
          black --check .

      - name: Unit tests (no slow/e2e)
        run: pytest -q -m "not e2e and not slow"
