
name: CI (Fork PR)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]
permissions: { contents: read }  # read-only

# Cancel superseded runs
concurrency:
  group: ci-fork-pr-${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest black ruff mypy pytest-mock pytest-qt pytest-timeout
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    # Code formatting
    - name: Ruff & Black
      run: |
        ruff check .
        black --check .
    
    # Static Type Checking   
    - name: Type check (optional)
      run: mypy .

    # Pytest
    - name: Fast tests
      run: pytest -q -m "not e2e and not slow"
