# This script detects all Python classes with docstrings in the plugins module
# and writes corresponding .. autoclass:: directives into a .rst file for Sphinx documentation.

name: Build and Test Sphinx Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the specified branches
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build-docs"
  build-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx
          pip install furo
      # Step 4: Run autodoc scripts
      - name: Generate autodoc for plugins
        run: python scripts/autodoc/plugins_generate_autodoc.py

      - name: Generate autodoc for metaclasses
        run: python scripts/autodoc/metaclasses_generate_autodoc.py

      # Step 5: Build HTML docs with Sphinx
      - name: Build Sphinx HTML docs (into `build/`)
        run: |
          sphinx-build -b html docs/source docs/build
          
      - name: List docs/build contents
        run: ls -R docs/build || echo "No build output found"

      # Step 6 (test purposes): Upload HTML as an artifact
      - name: Upload HTML docs
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-html-docs
          path: docs/build

      # Step 6: Deploy to GitHub Pages
      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v4
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: docs/build
      #    publish_branch: gh-pages
